### ISSUE TITLE
File Permission Issues

### ISSUE THREAD

**Issue by gnosisgithub** [LibraryOfCongress/bagit-python#146]
In the past bagit returned similar errors when anti-virus was running, but now completely removed, so not sure what these errors are about.  Note, the attempted payload has almost 3000 objects so maybe the issue only has to do with the files that bagit is reporting on?

Please suggest a solution or alt tool.  Thanks.

C:\Python27\Scripts>bagit.py --contact-name 'sklein'  C:\Users\sklein\Desktop\1st_scrape_2013_19\
2020-07-16 10:40:21,658 - INFO - Creating bag for directory C:\Users\sklein\Desktop\1st_scrape_2013_19
2020-07-16 10:40:23,003 - ERROR - The following files do not have read permissions:
('C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Albany_2015-09-30n?r Corr', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Bedarida_2016-02-01Export ?', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Habic_2017_01242', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Ljubicic_2018_01665', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Marin-Chollom_2017-06-02Latinoa?', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Mitrovic_2016_02850', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Ugurlu_2017_01219', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Barroso_2018_01800\\J??Dissertation?Dissertation- Final with revisions.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Davies_2017_01289\\IMPRESSIVE FAILURES ? MAVERICKS OF FILM AUTHORSHIP AND THE IMPOSSIBILITY OF SUCCESS IN HOLLYWOOD\x96\x96\xa9 DAVIES.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Florez_2016_00550\\Dissertation 03?30?16.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Freedman_2017_01202\\Z??Robins expenses?R. Freedman 4.26.2017. MALS Thesis.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Frisoli_2016_00369\\FINAL THESIS 4?15.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\McCool_2016_02851\\McCool - Revised Dissertation 1?16.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Parson_2016_00681\\C??Users?cparson?Desktop?Chad Parson Dissertation REVISED FINAL FOR DEPOSIT 20160913 v1.1.pdf', 'C:\\Users\\sklein\\Desktop\\1st_scrape_2013_19\\objects\\Rubin_2017_01170\\Max Rubin Capstone Final 4?26.pdf')
2020-07-16 10:40:23,003 - ERROR - An error occurred creating a bag in C:\Users\sklein\Desktop\1st_scrape_2013_19
Traceback (most recent call last):
  File "C:\Python27\Scripts\bagit.py", line 206, in make_bag
    _("Read permissions are required to calculate file fixities")
BagError: Read permissions are required to calculate file fixities
2020-07-16 10:40:23,003 - ERROR - Failed to create bag in C:\Users\sklein\Desktop\1st_scrape_2013_19\: Read permissions are required to calculate file fixities
Traceback (most recent call last):
  File "C:\Python27\Scripts\bagit.py", line 1598, in main
    checksums=args.checksums,
  File "C:\Python27\Scripts\bagit.py", line 206, in make_bag
    _("Read permissions are required to calculate file fixities")
BagError: Read permissions are required to calculate file fixities

**Comment by gnosisgithub** [comment]
Special diacritics was tripping up bagit. I cleaned up the filesnames and all seems good now.
